language: python
python:
  - "2.7"

install:
  - "bin/bootstrap.sh $VIRTUAL_ENV"

script:
  - python setup.py test
  - tests/run.sh

notifications:
  email:
    - noah.hoffman@gmail.com
    - crosenth@uw.edu
