sudo: false
language: python
python: 2.7
cache: pip

addons:
  apt:
    packages:
      # scipy dependencies
      - gfortran
      - libopenblas-dev
      - liblapack-dev

install: 
  - "pip install scipy==0.15.1"
  - "bin/bootstrap.sh $VIRTUAL_ENV"

script:
  - "python setup.py test"
  - "tests/run.sh"

#notifications:
#  email:
#    - noah.hoffman@gmail.com
