language: python
python:
  - "2.7"

before_install:
  - "sudo apt-get build-dep python-scipy"

install: travis_wait "bin/bootstrap.sh $VIRTUAL_ENV"

script:
  - python setup.py test
  - tests/run.sh

notifications:
  email:
    - noah.hoffman@gmail.com
